using UnityEngine;

/// <summary>
/// Baked curve data asset. Generated by CurveGeneratorWindow, consumed by GPU simulations.
/// Stores uniformly sampled positions + tangents for efficient GPU lookup.
/// </summary>
[CreateAssetMenu(menuName = "Mine/Curve Asset", fileName = "NewCurve")]
public class CurveAsset : ScriptableObject
{
    public enum CurveType
    {
        CatmullRom,
        Bezier,
        // Future: BSpline, Hermite
    }

    public enum CurveDimension
    {
        XYZ,  // full 3D
        XY,   // locked to XY plane
        XZ,   // locked to XZ plane
        YZ,   // locked to YZ plane
    }

    [Header("Source")]
    public CurveType curveType;
    public CurveDimension dimension;
    public bool loop;

    [Header("Baked Data")]
    public Vector3[] positions;
    public Vector3[] tangents;
    public float[] arcLengths;    // cumulative arc length per sample
    public Vector3[] normals;     // curvature normal (points toward bend center)
    public float[] curvatures;    // scalar curvature κ = 1/radius
    public float totalLength;
    public int sampleCount;

    [Header("Info")]
    public int controlPointCount;
    public Vector3[] controlPointPositions; // snapshot of CP world positions at bake time

    /// <summary>Get a normalized (0-1) curve sample. t is clamped to [0,1].</summary>
    public void Sample(float t, out Vector3 position, out Vector3 tangent)
    {
        if (positions == null || positions.Length < 2)
        {
            position = Vector3.zero;
            tangent = Vector3.forward;
            return;
        }

        t = Mathf.Clamp01(t);
        float indexFloat = t * (positions.Length - 1);
        int i0 = Mathf.Min((int)indexFloat, positions.Length - 1);
        int i1 = Mathf.Min(i0 + 1, positions.Length - 1);
        float frac = indexFloat - i0;

        position = Vector3.Lerp(positions[i0], positions[i1], frac);
        tangent = Vector3.Slerp(tangents[i0], tangents[i1], frac);
    }
}
